# Generated by Django 4.0.4 on 2022-06-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_productimages_notes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='product_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='product_price',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
