# Generated by Django 4.0.4 on 2022-06-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_note_cart_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
