# Generated by Django 4.0.4 on 2022-06-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
